{
 "title": "Omi Services Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Managed transcription (Backend-listen + Modulate)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Backend-listen request count (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "RPS",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "custom-domains-api-omi-me-backend-listen-49a4-be",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/backend_request_count"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Backend-listen request latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "histogram_quantile(0.50, sum by (\"le\")(rate({\"__name__\"=\"loadbalancing_googleapis_com:https_backend_latencies_bucket\",\"monitored_resource\"=\"https_lb_rule\",\"backend_target_name\"=\"custom-domains-api-omi-me-backend-listen-49a4-be\"}[1m])))\n",
      "projectName": "based-hardware",
      "step": "10s"
     },
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "custom-domains-api-omi-me-backend-listen-49a4-be",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/backend_latencies"
      ],
      "groupBys": [
       "resource.label.backend_target_name"
      ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "promQLQuery": {
      "expr": "histogram_quantile(0.95, sum by (\"le\")(rate({\"__name__\"=\"loadbalancing_googleapis_com:https_backend_latencies_bucket\",\"monitored_resource\"=\"https_lb_rule\",\"backend_target_name\"=\"custom-domains-api-omi-me-backend-listen-49a4-be\"}[1m])))\n",
      "projectName": "based-hardware",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "promQLQuery": {
      "expr": "histogram_quantile(0.99, sum by (\"le\")(rate({\"__name__\"=\"loadbalancing_googleapis_com:https_backend_latencies_bucket\",\"monitored_resource\"=\"https_lb_rule\",\"backend_target_name\"=\"custom-domains-api-omi-me-backend-listen-49a4-be\"}[1m])))\n",
      "projectName": "based-hardware",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Backend-listen error rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "4XX",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "custom-domains-api-omi-me-backend-listen-49a4-be",
       "AND",
       "metric.label.response_code_class",
       "=",
       "400",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/backend_request_count"
      ],
      "groupBys": [
       "metric.label.response_code_class"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "5XX",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "custom-domains-api-omi-me-backend-listen-49a4-be",
       "AND",
       "metric.label.response_code_class",
       "=",
       "500",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/backend_request_count"
      ],
      "groupBys": [
       "metric.label.response_code_class"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Backend-listen response code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "aliasBy": "{{metric.label.response_code}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "custom-domains-api-omi-me-backend-listen-49a4-be",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/backend_request_count"
      ],
      "groupBys": [ "metric.label.response_code" ],
      "perSeriesAligner": "ALIGN_DELTA",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Backend-listen replica count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"prod-omi-backend-listen\"})",
     "legendFormat": "Replicas"
    }
   ]
  },
  {
   "title": "HPA metric status - backend_listen_active_ws_connections_per_pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_target_metric{horizontalpodautoscaler=\"prod-omi-backend-listen\",metric_name=\"backend_listen_active_ws_connections_per_pod\"}",
     "legendFormat": "{{metric_name}} - Current"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"prod-omi-backend-listen\",metric_name=\"backend_listen_active_ws_connections_per_pod\"}",
     "legendFormat": "{{metric_name}} - Target"
    }
   ]
  },
  {
   "title": "Backend-listen active WS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(backend_listen_active_ws_connections{job=\"backend-listen-metrics\"})",
     "legendFormat": "WS"
    }
   ]
  },
  {
   "title": "Backend-listen avg. WS per pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(backend_listen_active_ws_connections{job=\"backend-listen-metrics\"})",
     "legendFormat": "Avg. WS per pod"
    }
   ]
  },
  {
   "title": "Backend-listen WS per pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "backend_listen_active_ws_connections{job=\"backend-listen-metrics\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transcription Service - RPS (Log based)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({service_name=\"backend-listen\"} |= `_listen` [$__auto]))-count(rate({service_name=\"backend-listen\"} |~ `_listen.*end` [$__auto]))",
     "legendFormat": "listen start"
    },
    {
     "direction": "backward",
     "expr": "count(rate({service_name=\"backend-listen\"} |~ `_listen.*end` [$__auto]))",
     "legendFormat": "listen end"
    }
   ]
  },
  {
   "title": "Transcription Service Error Rate (Log based)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({service_name=\"backend-listen\"} |= `ASGI callable returned without sending` [$__auto]))",
     "legendFormat": "Handshake failure"
    },
    {
     "direction": "backward",
     "expr": "count(rate({service_name=\"backend-listen\"} |= `Token expired` [$__auto]))",
     "legendFormat": "Token expired"
    }
   ]
  },
  {
   "title": "Transcription Service Error Rate: Data corrupted",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({service_name=\"backend-listen\"} |= `Could not process data: error b'corrupted stream` [$__auto]))",
     "legendFormat": "Corrupted Stream"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Backend - Request count (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "RPS",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "custom-domains-api-omi-me-backend-49a4-be",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/backend_request_count"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": " Backend - Max concurrent requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "aliasBy": "p50",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "backend",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/max_request_concurrencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p95",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "backend",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/max_request_concurrencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p99",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "backend",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/max_request_concurrencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": " Backend - Request latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "aliasBy": "p50",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "backend",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/request_latencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p95",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "backend",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/request_latencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p99",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "backend",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/request_latencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Backend - Error rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "4XX",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "custom-domains-api-omi-me-backend-49a4-be",
       "AND",
       "metric.label.response_code_class",
       "=",
       "400",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/backend_request_count"
      ],
      "groupBys": [
       "metric.label.response_code_class"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "5XX",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "custom-domains-api-omi-me-backend-49a4-be",
       "AND",
       "metric.label.response_code_class",
       "=",
       "500",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/backend_request_count"
      ],
      "groupBys": [
       "metric.label.response_code_class"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Backend - Response code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "targets": [
    {
     "aliasBy": "{{metric.label.response_code}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "custom-domains-api-omi-me-backend-49a4-be",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/backend_request_count"
      ],
      "groupBys": [ "metric.label.response_code" ],
      "perSeriesAligner": "ALIGN_DELTA",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Backend - Instance count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "aliasBy": "{{metric.label.state}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [
       "resource.label.service_name",
       "=",
       "backend",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/instance_count"
      ],
      "groupBys": [ "metric.label.state" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  { "title": "Pusher (on GKE)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Pusher - Request count (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "RPS",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "k8s1-5245918b-prod-omi-backend-prod-omi-pusher-8080-a5e82c64",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/internal/backend_request_count"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Pusher - Request latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "histogram_quantile(0.50, sum by (\"le\")(rate({\"__name__\"=\"loadbalancing_googleapis_com:https_internal_backend_latencies_bucket\",\"monitored_resource\"=\"internal_http_lb_rule\",\"backend_target_name\"=\"k8s1-5245918b-prod-omi-backend-prod-omi-pusher-8080-a5e82c64\"}[1m])))",
      "projectName": "based-hardware",
      "step": "10s"
     },
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "custom-domains-api-omi-me-backend-listen-49a4-be",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/backend_latencies"
      ],
      "groupBys": [
       "resource.label.backend_target_name"
      ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "promQLQuery": {
      "expr": "histogram_quantile(0.95, sum by (\"le\")(rate({\"__name__\"=\"loadbalancing_googleapis_com:https_internal_backend_latencies_bucket\",\"monitored_resource\"=\"internal_http_lb_rule\",\"backend_target_name\"=\"k8s1-5245918b-prod-omi-backend-prod-omi-pusher-8080-a5e82c64\"}[1m])))",
      "projectName": "based-hardware",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "promQLQuery": {
      "expr": "histogram_quantile(0.99, sum by (\"le\")(rate({\"__name__\"=\"loadbalancing_googleapis_com:https_internal_backend_latencies_bucket\",\"monitored_resource\"=\"internal_http_lb_rule\",\"backend_target_name\"=\"k8s1-5245918b-prod-omi-backend-prod-omi-pusher-8080-a5e82c64\"}[1m])))",
      "projectName": "based-hardware",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Pusher - Error rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "4XX",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "k8s1-5245918b-prod-omi-backend-prod-omi-pusher-8080-a5e82c64",
       "AND",
       "metric.label.response_code_class",
       "=",
       "400",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/internal/backend_request_count"
      ],
      "groupBys": [
       "metric.label.response_code_class"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "5XX",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "k8s1-5245918b-prod-omi-backend-prod-omi-pusher-8080-a5e82c64",
       "AND",
       "metric.label.response_code_class",
       "=",
       "500",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/internal/backend_request_count"
      ],
      "groupBys": [
       "metric.label.response_code_class"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Pusher - Response code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 57 },
   "targets": [
    {
     "aliasBy": "{{metric.label.response_code}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "k8s1-5245918b-prod-omi-backend-prod-omi-pusher-8080-a5e82c64",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/internal/backend_request_count"
      ],
      "groupBys": [ "metric.label.response_code" ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Pusher - Replica count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 57 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"prod-omi-pusher\"})",
     "legendFormat": "Replicas"
    }
   ]
  },
  {
   "title": "Pusher - HPA replica status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 57 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"prod-omi-pusher\"})",
     "legendFormat": "Current replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{horizontalpodautoscaler=\"prod-omi-pusher\"}",
     "legendFormat": "Min replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=\"prod-omi-pusher\"}",
     "legendFormat": "Max replicas"
    }
   ]
  },
  {
   "title": "HPA metric status - pusher_active_ws_connections_per_pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_target_metric{horizontalpodautoscaler=\"prod-omi-pusher\",metric_name=\"pusher_active_ws_connections_per_pod\"}",
     "legendFormat": "{{metric_name}} - Current"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"prod-omi-pusher\",metric_name=\"pusher_active_ws_connections_per_pod\"}",
     "legendFormat": "{{metric_name}} - Target"
    }
   ]
  },
  {
   "title": "Pusher active WS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pusher_active_ws_connections{job=\"pusher-metrics\"})",
     "legendFormat": "WS"
    }
   ]
  },
  {
   "title": "Pusher avg. WS per pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(pusher_active_ws_connections{job=\"pusher-metrics\"})",
     "legendFormat": "Avg. WS per pod"
    }
   ]
  },
  {
   "title": "Pusher WS per pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pusher_active_ws_connections{job=\"pusher-metrics\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "VAD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "VAD - Request count (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "RPS",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "k8s1-5245918b-prod-omi-backend-prod-omi-vad-8080-cb5bc8b7",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/internal/backend_request_count"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "VAD - Request latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "histogram_quantile(0.50, sum by (\"le\")(rate({\"__name__\"=\"loadbalancing_googleapis_com:https_internal_backend_latencies_bucket\",\"monitored_resource\"=\"internal_http_lb_rule\",\"backend_target_name\"=\"k8s1-5245918b-prod-omi-backend-prod-omi-vad-8080-cb5bc8b7\"}[1m])))",
      "projectName": "based-hardware",
      "step": "10s"
     },
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "custom-domains-api-omi-me-backend-listen-49a4-be",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/backend_latencies"
      ],
      "groupBys": [
       "resource.label.backend_target_name"
      ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "promQLQuery": {
      "expr": "histogram_quantile(0.95, sum by (\"le\")(rate({\"__name__\"=\"loadbalancing_googleapis_com:https_internal_backend_latencies_bucket\",\"monitored_resource\"=\"internal_http_lb_rule\",\"backend_target_name\"=\"k8s1-5245918b-prod-omi-backend-prod-omi-vad-8080-cb5bc8b7\"}[1m])))",
      "projectName": "based-hardware",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "promQLQuery": {
      "expr": "histogram_quantile(0.99, sum by (\"le\")(rate({\"__name__\"=\"loadbalancing_googleapis_com:https_internal_backend_latencies_bucket\",\"monitored_resource\"=\"internal_http_lb_rule\",\"backend_target_name\"=\"k8s1-5245918b-prod-omi-backend-prod-omi-vad-8080-cb5bc8b7\"}[1m])))",
      "projectName": "based-hardware",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "VAD - Error rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "4XX",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "k8s1-5245918b-prod-omi-backend-prod-omi-vad-8080-cb5bc8b7",
       "AND",
       "metric.label.response_code_class",
       "=",
       "400",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/internal/backend_request_count"
      ],
      "groupBys": [
       "metric.label.response_code_class"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "5XX",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "k8s1-5245918b-prod-omi-backend-prod-omi-vad-8080-cb5bc8b7",
       "AND",
       "metric.label.response_code_class",
       "=",
       "500",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/internal/backend_request_count"
      ],
      "groupBys": [
       "metric.label.response_code_class"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "VAD - Response code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 82 },
   "targets": [
    {
     "aliasBy": "{{metric.label.response_code}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "k8s1-5245918b-prod-omi-backend-prod-omi-vad-8080-cb5bc8b7",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/internal/backend_request_count"
      ],
      "groupBys": [ "metric.label.response_code" ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "VAD - HPA replica status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 82 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"prod-omi-vad\"})",
     "legendFormat": "Current replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{horizontalpodautoscaler=\"prod-omi-vad\"}",
     "legendFormat": "Min replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=\"prod-omi-vad\"}",
     "legendFormat": "Max replicas"
    }
   ]
  },
  {
   "title": "VAD - HPA metric status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_target_metric{horizontalpodautoscaler=\"prod-omi-vad\",metric_name=\"cpu\",metric_target_type=\"utilization\"}",
     "legendFormat": "{{metric_name}} - Current"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"prod-omi-vad\",metric_name=\"cpu\"}",
     "legendFormat": "{{metric_name}} - Target"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_target_metric{horizontalpodautoscaler=\"prod-omi-vad\",metric_name=\"memory\",metric_target_type=\"utilization\"}",
     "legendFormat": "{{metric_name}} - Current"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"prod-omi-vad\",metric_name=\"memory\"}",
     "legendFormat": "{{metric_name}} - Target"
    }
   ]
  },
  { "title": "Backend-sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Backend-sync - Request count (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "RPS",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "custom-domains-api-omi-me-backend-sync-49a4-be",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/backend_request_count"
      ],
      "groupBys": [
       "resource.label.backend_target_name"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": " Backend-sync - Max concurrent requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 102 },
   "targets": [
    {
     "aliasBy": "p50",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "backend-sync",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/max_request_concurrencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p95",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "backend-sync",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/max_request_concurrencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p99",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "backend-sync",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/max_request_concurrencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": " Backend-sync - Request latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 102 },
   "targets": [
    {
     "aliasBy": "p50",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "backend-sync",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/request_latencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p95",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "backend-sync",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/request_latencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p99",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "backend-sync",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/request_latencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Backend-sync - Error rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "4XX",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "custom-domains-api-omi-me-backend-sync-49a4-be",
       "AND",
       "metric.label.response_code_class",
       "=",
       "400",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/backend_request_count"
      ],
      "groupBys": [
       "metric.label.response_code_class"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "5XX",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "custom-domains-api-omi-me-backend-sync-49a4-be",
       "AND",
       "metric.label.response_code_class",
       "=",
       "500",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/backend_request_count"
      ],
      "groupBys": [
       "metric.label.response_code_class"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Backend-sync - Response code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 108 },
   "targets": [
    {
     "aliasBy": "{{metric.label.response_code}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "custom-domains-api-omi-me-backend-sync-49a4-be",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/backend_request_count"
      ],
      "groupBys": [ "metric.label.response_code" ],
      "perSeriesAligner": "ALIGN_DELTA",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Backend-sync - Instance count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 108 },
   "targets": [
    {
     "aliasBy": "{{metric.label.state}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [
       "resource.label.service_name",
       "=",
       "backend-sync",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/instance_count"
      ],
      "groupBys": [ "metric.label.state" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  { "title": "Cloud Armor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "Cloud Armor - Denied requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 122 },
   "targets": [
    {
     "aliasBy": "Denied requests",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "logging.googleapis.com/user/cloud_armor_policy_denied_requests"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MAX",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Cloud Armor - Denied requests per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "Denied RPS",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "logging.googleapis.com/user/cloud_armor_policy_denied_requests"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  { "title": "OpenAI(LLM)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "OpenAI - Quota exceeded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 129 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({service_name=~\"backend-listen\"} |~ `429.*(quota)` [$__auto])) or vector(0)",
     "legendFormat": "Error"
    }
   ]
  }
 ]
}